#!/bin/sh
exec tail -n +3 $0
### GRUBswitch_script v1.1 ###
### FINDING, HASH-CHECKING AND EXECUTING 'SWITCH.GRB' FILE ###

## Try to find SWITCH.GRB file in drives
## extend for loop numbers if your system might have
## more drives, including plugged-in USB drives
SWITCH_GRB_FOLDER=
for i in 0 1 2 3 4 5 6 7 8 9
do
	if [ -e (hd${i})/SWITCH.GRB ]
	then	SWITCH_GRB_FOLDER="(hd${i})"
	fi

	if [ -e (hd${i},1)/SWITCH.GRB ]
	then	SWITCH_GRB_FOLDER="(hd${i},1)"
	fi
done

## check SWITCH.GRB against hashes
if [ -n "${SWITCH_GRB_FOLDER}" ]
then
	MATCHED=true		## if the hashes folder does not exist, don't check
	if [ -e ${prefix}/grub_switch_hashes ]
	then
		echo "Found hash folder. Continuing..."
		MATCHED=false
		for i in 0 1 2 3 4 5 6 7 8 9 a b c d e f
		do
			filename=${prefix}/grub_switch_hashes/${i}.sha512
			if [ -e $filename ]
			then
				echo -n "checking against hash #${i}: "
				if sha512sum  --check ${filename} --prefix ${SWITCH_GRB_FOLDER}
				then
					MATCHED=true
				fi
			fi
		done
		if [ false = $MATCHED ]
		then
			echo "SWITCH.GRB didn't match any of the stored hashes and won't be run."
			sleep 3
			# show menu for sure
			unset timeout
			unset default
			unset fallback
			timeout_style="menu"
		fi
	else
		echo "Didn't find hash folder."
	fi
else
	MATCHED=false		## if SWITCH.GRB not found, don't execute either
fi


## execute SWITCH.GRB file if it exists and did not fail hash check
if [ true = $MATCHED ]
then
	source ${SWITCH_GRB_FOLDER}/SWITCH.GRB
fi
